version: "3.7"

services:
  web:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - "${INVOICE_APP_EXPOSED:-80}:80"
    restart: on-failure
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_DATABASE=db_name
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
