home:
    path: /
    controller: App\Action\HomePage::handle

invoice_listing:
    path: /invoice
    controller: App\Action\Invoice\Listing::handle

invoice_details:
    path: /invoice/{id}
    controller: App\Action\Invoice\Details::handle
    requirements:
        id: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}'